requests:
  stock_url: "https://financialmodelingprep.com/stable/historical-chart/5min?symbol={symbol}&from={fromdate}&to={todate}&apikey={api_key}"
  eod_url: "https://financialmodelingprep.com/stable/historical-price-eod/full?symbol={symbol}&from={fromdate}&to={todate}&apikey={api_key}"

columns:
  name_col: 'name'
  symbol_col: 'SYMBOL'
  fromdate_col: 'start_date'
  todate_col: 'end_date'
  date_col: 'DATE'
  open_col: 'OPEN'
  high_col: 'HIGH'
  low_col: 'LOW'
  close_col: 'CLOSE'
  volume_col: 'VOLUME'

run_date: '2024-06-01'

select_cols:
  - "symbol"
  - "date"
  - "open"
  - "high"
  - "low"
  - "close"
  - "volume"


feature_cols:
  - "open"
  - "high"
  - "low"
  - "volume"


